openapi: '3.0.3'
info:
  title: Cafes API
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  /cafes:
    get:
      summary: Get all cafes
      operationId: findAllCafes
      responses:
        '200':
          description: A list of cafes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CafeDtoWithoutDrinks'
  /cafes/detail/{id}:
    get:
      summary: Get cafe details
      operationId: findOneCafe
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the cafe
      responses:
        '200':
          description: Cafe details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CafeDto'
components:
  schemas:
    CafeDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        address:
          type: string
        image_urls:
          type: array
          items:
            type: string
        price_range:
          type: string
          enum:
            - low
            - medium
            - high
        style:
          type: string
          enum:
            - modern
            - traditional
            - vintage
            - outdoor
            - workspace
        google_rating:
          type: number
          format: float
        opening_time:
          type: string
          format: time
        closing_time:
          type: string
          format: time
        distance_from_sun:
          type: number
          format: float
        drinks:
          type: array
          items:
            $ref: '#/components/schemas/Drink'
    CafeDtoWithoutDrinks:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        address:
          type: string
        image_urls:
          type: array
          items:
            type: string
        price_range:
          type: string
          enum:
            - low
            - medium
            - high
        style:
          type: string
          enum:
            - modern
            - traditional
            - vintage
            - outdoor
            - workspace
        google_rating:
          type: number
          format: float
        opening_time:
          type: string
          format: time
        closing_time:
          type: string
          format: time
        distance_from_sun:
          type: number
          format: float
    Drink:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
          enum:
            - coffee
            - tea
            - smoothie
            - juice
            - other
        price:
          type: number
          format: float
        description:
          type: string
        image_url:
          type: string
        is_available:
          type: boolean